default_branch: main

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: ucsb-cs-course-repos/course-repo-jekyll-theme@pcmultlectwithmasterormain


url: https://ucsb-cs32.github.io 
baseurl: "/w21"

course: "CS32"
qtr: "W21"
quarter: "Winter 2021"
piazza_url: https://piazza.com/ucsb/fall2020/cs32/home
gauchospace_course_page:
gradescope_class_url: https://www.gradescope.com/courses/193319

instructor_name: "Zoë Wood"
ta_list: ""
ta_list_full: "Aishwarya Manickam Rameshbabu, Bowen Zhang, Suriya Dakshina Murthy"
mentors_list: "Alan Roddick, Bethany Long, Qiru Hu"
discussion_section_times: "noon, 1pm"

github_url: https://github.com/ucsb-cs32/w21
mentor_url:

on_campus: http://proquest.safaribooksonline.com
off_campus: http://proquest.safaribooksonline.com.proxy.library.ucsb.edu:2048


start_week: 1
start_date: 2021-01-03
num_weeks: 10
extra_exam_week: true

cal_dates: >
  [
    {"label":"W21 1st day of instruction", "date":"2021-01-04" },	
    {"label":"Univ Holiday", "date":"2021-01-18" , "holiday": true},
    {"label":"Univ Holiday", "date":"2021-01-15" , "holiday": true},
    {"label":"W21 instruction ends", "date":"2021-03-12" },
    {"label":"W21 finals start", "date":"2021-03-13" },
    {"label":"W21 finals end", "date":"2021-03-19" },
    {"label":"W21 qtr ends", "date":"2021-03-19" }
  ]


kramdown:
   parse_block_html: true
   default_lang: cpp

exclude:
   - vendor
   - _hwk/keep
   - _lab/keep
   - _exam/keep
   - _lectures/keep
   - _info/keep        
include:
   - _pages
   
timezone: America/Los_Angeles

collections:
  hwk:
    output: true
    permalink: /hwk/:path/
    last_before: false
  lab:
    output: true
    permalink: /lab/:path/
    last_before: false
  labWIP:
    output: true
    permalink: /labWIP/:path/
    last_before: false
  exam:
    output: true
    permalink: /exam/:path/
  info:
    output: true
    permalink: /info/:path/
  lectures:
    output: true
    permalink: /lectures/:path/


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  - 
    scope:
      path: ""
      type: lectures
    values:
      layout: lecture
  - 
    scope:
      path: ""
      type: hwk
    values:
      layout: hwk
  - 
    scope:
      path: ""
      type: lab
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: labWIP
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: exam
    values:
      layout: exam_info
  - 
    scope:
      path: ""
      type: info
    values:
      layout: default
  -
    scope:
      path: "syllabus.md"
      type: info
    values:
      layout: handout
