default_branch: main

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: ucsb-cs-course-repos/course-repo-jekyll-theme@pcmultlectwithmasterormain


url: https://ucsb-cs32.github.io 
baseurl: "/s21"

course: "CS32"
qtr: "S21"
quarter: "Spring 2021"
gauchospace_course_page: https://gauchospace.ucsb.edu/
gradescope_class_url: https://gradescope.com
piazza: https://piazza.com/ucsb/winter2021/cs32s21


instructor_name: "Zoë Wood"
ta_list: "Suriya, Aishwarya"
ta_list_full: "Suriya Dakshina Murthy, Aishwarya M Rameshbabu"
mentors_list: "Alan, Bethany, and Qiru"
mentors_list_full: "Alan Roddick, Bethany Long, Qiru Hu"
discussion_section_times: "noon, 1pm"

github_url: https://github.com/ucsb-cs32/s21
mentor_url:

on_campus: http://proquest.safaribooksonline.com
off_campus: http://proquest.safaribooksonline.com.proxy.library.ucsb.edu:2048


start_week: 1
start_date: 2021-03-28
num_weeks: 10
extra_exam_week: true

cal_dates: >
  [
    {"label":"S21 1st day of instruction", "date":"2021-03-29" },	
    {"label":"Univ Holiday", "date":"2021-05-31" , "holiday": true},
    {"label":"S21 instruction ends", "date":"2021-06-04" },
    {"label":"S21 finals start", "date":"2021-06-05" },
    {"label":"CS156 Final noon-3pm", "date":"2021-06-08" },
    {"label":"W21 finals end", "date":"2021-06-11" },
    {"label":"W21 qtr ends", "date":"2021-06-11" }
  ]


kramdown:
   parse_block_html: true
   default_lang: cpp

exclude:
   - vendor
   - _hwk/keep
   - _lab/keep
   - _exam/keep
   - _lectures/keep
   - _info/keep        
include:
   - _pages
   
timezone: America/Los_Angeles

collections:
  hwk:
    output: true
    permalink: /hwk/:path/
    last_before: false
  lab:
    output: true
    permalink: /lab/:path/
    last_before: false
  labWIP:
    output: true
    permalink: /labWIP/:path/
    last_before: false
  exam:
    output: true
    permalink: /exam/:path/
  info:
    output: true
    permalink: /info/:path/
  lectures:
    output: true
    permalink: /lectures/:path/


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  - 
    scope:
      path: ""
      type: lectures
    values:
      layout: lecture
  - 
    scope:
      path: ""
      type: hwk
    values:
      layout: hwk
  - 
    scope:
      path: ""
      type: lab
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: labWIP
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: exam
    values:
      layout: exam_info
  - 
    scope:
      path: ""
      type: info
    values:
      layout: default
  -
    scope:
      path: "syllabus.md"
      type: info
    values:
      layout: handout
